services:
  - type: web
    name: sistema-backend-gestao-fitpro
    env: node
    plan: free
    buildCommand: yarn --frozen-lockfile install && yarn prisma generate && yarn build
    startCommand: yarn start
    autoDeploy: true
